#!/bin/bash

min_msg_len=20
min_msg_words=3

original_message="$(test -f "$1" && cat "$1" || echo "")"

ticket=$(git symbolic-ref HEAD | sed 's,^.*/\([A-Z]*-[0-9]*\)-.*$,\1,1')
# remove ticket number from message
message="$(echo "$original_message" | sed "s,^i[^/]*/[^/]*/,,g;,${ticket},,g;s,  , ,g;s,()$,,g;s,^:,,g" | xargs)"

if [ ${#message} -le $min_msg_len ] ; then
  echo "Commit message too short. Need at least ${min_msg_len} characters." > /dev/stderr
  exit 1
fi

if [ $(( $(echo "$message" | wc -w) )) -le $min_msg_words ] ; then
  echo "Commit message too short. Need at least ${min_msg_words} words. Please use sensful phrases." > /dev/stderr
  exit 1
fi

if [ ! -z "$ticket" ]; then
  if [[ ! $message =~ $ticket ]] ; then
    message="${ticket} ${message}"
  fi
fi

echo "$message" > "$1"
echo "$message"

